_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 512
learning_rate:
    value: 0.0002
num_epochs:
    value: 20
vq_kwargs:
    value:
        affine_lr: 0
        beta: 0.25
        dim: -1
        num_codes: 2048
        replace_freq: 20
        sync_nu: 2
